url: https://evilon.github.io/

# Site settings
title: Jani's home
email:
description: "Jani Kentt채l채's non-work(ish) page.'"


# Team names, titles and social links
people:
- name: Jani Kentt채l채
  pic: janikenttala.png
  position: Free
  social:
    - title: twitter
      url: https://twitter.com/janikenttala
    - title: medium
      url: https://medium.com/@janikenttala
    - title: linkedin
      url: https://www.linkedin.com/in/janikenttala
    - title: github
      url: https://github.com/evilon
    - title: soundcloud
      url: https://soundcloud.com/jani-kenttaelae/
    - title: instagram
      url: https://www.instagram.com/janikenttala

    #- title: facebook
    #  url: #
    #- title: stack-overflow
    #  url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/evilon
# Postal address (add as many lines as necessary)
address:
  - line: Oulu

# Build settings
markdown: kramdown
permalink: pretty
